package com.cloudscaleqa.model;

// Generated Jan 25, 2018 1:06:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fronendtech generated by hbm2java
 */
@Entity
@Table(name = "fronendtech")
public class Fronendtech implements java.io.Serializable {

	/**
	 */
	private static final long serialVersionUID = -4197283089009713428L;
	private String value;
	private String id;
	private String name;
	private Set<Toolfrontendtechassoc> toolfrontendtechassocs = new HashSet<Toolfrontendtechassoc>(
			0);

	public Fronendtech() {
	}

	public Fronendtech(String value, String id, String name) {
		this.value = value;
		this.id = id;
		this.name = name;
	}

	public Fronendtech(String value, String id, String name,
			Set<Toolfrontendtechassoc> toolfrontendtechassocs) {
		this.value = value;
		this.id = id;
		this.name = name;
		this.toolfrontendtechassocs = toolfrontendtechassocs;
	}

	@Id
	@Column(name = "Value", unique = true, nullable = false, length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ID", nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fronendtech")
	public Set<Toolfrontendtechassoc> getToolfrontendtechassocs() {
		return this.toolfrontendtechassocs;
	}

	public void setToolfrontendtechassocs(
			Set<Toolfrontendtechassoc> toolfrontendtechassocs) {
		this.toolfrontendtechassocs = toolfrontendtechassocs;
	}

}
