package com.cloudscaleqa.model;

// Generated Jan 25, 2018 1:06:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mobos generated by hbm2java
 */
@Entity
@Table(name = "mobos", uniqueConstraints = @UniqueConstraint(columnNames = "Value"))
public class Mobos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4450583161979974155L;
	private Integer id;
	private String name;
	private String value;
	private Set<Toolmobosassoc> toolmobosassocs = new HashSet<Toolmobosassoc>(0);

	public Mobos() {
	}

	public Mobos(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public Mobos(String name, String value, Set<Toolmobosassoc> toolmobosassocs) {
		this.name = name;
		this.value = value;
		this.toolmobosassocs = toolmobosassocs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value", unique = true, nullable = false, length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mobos")
	public Set<Toolmobosassoc> getToolmobosassocs() {
		return this.toolmobosassocs;
	}

	public void setToolmobosassocs(Set<Toolmobosassoc> toolmobosassocs) {
		this.toolmobosassocs = toolmobosassocs;
	}

}
