package com.cloudscaleqa.model;

// Generated Jan 25, 2018 1:06:55 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Toolbrowserassoc generated by hbm2java
 */
@Entity
@Table(name = "toolbrowserassoc")
public class Toolbrowserassoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5739651356552627507L;
	private Integer id;
	private Tool tool;
	private Browsers browsers;

	public Toolbrowserassoc() {
	}

	public Toolbrowserassoc(Tool tool, Browsers browsers) {
		this.tool = tool;
		this.browsers = browsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TVal", nullable = false)
	public Tool getTool() {
		return this.tool;
	}

	public void setTool(Tool tool) {
		this.tool = tool;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRVal", nullable = false)
	public Browsers getBrowsers() {
		return this.browsers;
	}

	public void setBrowsers(Browsers browsers) {
		this.browsers = browsers;
	}

}
