package com.cloudscaleqa.model;

// Generated Jan 25, 2018 1:06:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Toolgroup generated by hbm2java
 */
@Entity
@Table(name = "toolgroup")
public class Toolgroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6897343212424033856L;
	private String value;
	private String id;
	private String name;
	private String imgSrc;
	private Set<Toolgrouptoolassoc> toolgrouptoolassocs = new HashSet<Toolgrouptoolassoc>(
			0);
	private Set<Userrecommendation> userrecommendations = new HashSet<Userrecommendation>(
			0);

	public Toolgroup() {
	}

	public Toolgroup(String value, String id, String name, String imgSrc) {
		this.value = value;
		this.id = id;
		this.name = name;
		this.imgSrc = imgSrc;
	}

	public Toolgroup(String value, String id, String name, String imgSrc,
			Set<Toolgrouptoolassoc> toolgrouptoolassocs,
			Set<Userrecommendation> userrecommendations) {
		this.value = value;
		this.id = id;
		this.name = name;
		this.imgSrc = imgSrc;
		this.toolgrouptoolassocs = toolgrouptoolassocs;
		this.userrecommendations = userrecommendations;
	}

	@Id
	@Column(name = "Value", unique = true, nullable = false, length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ID", nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Img_src", nullable = false, length = 256)
	public String getImgSrc() {
		return this.imgSrc;
	}

	public void setImgSrc(String imgSrc) {
		this.imgSrc = imgSrc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toolgroup")
	public Set<Toolgrouptoolassoc> getToolgrouptoolassocs() {
		return this.toolgrouptoolassocs;
	}

	public void setToolgrouptoolassocs(
			Set<Toolgrouptoolassoc> toolgrouptoolassocs) {
		this.toolgrouptoolassocs = toolgrouptoolassocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toolgroup")
	public Set<Userrecommendation> getUserrecommendations() {
		return this.userrecommendations;
	}

	public void setUserrecommendations(
			Set<Userrecommendation> userrecommendations) {
		this.userrecommendations = userrecommendations;
	}

}
