package com.cloudscaleqa.model;

// Generated Jan 25, 2018 1:06:55 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Toolosassoc generated by hbm2java
 */
@Entity
@Table(name = "toolosassoc")
public class Toolosassoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6437841740863168883L;
	private Integer id;
	private Tool tool;
	private Os os;

	public Toolosassoc() {
	}

	public Toolosassoc(Tool tool, Os os) {
		this.tool = tool;
		this.os = os;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TVal", nullable = false)
	public Tool getTool() {
		return this.tool;
	}

	public void setTool(Tool tool) {
		this.tool = tool;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OSVal", nullable = false)
	public Os getOs() {
		return this.os;
	}

	public void setOs(Os os) {
		this.os = os;
	}

}
