package com.cloudscaleqa.model;

// Generated Jan 25, 2018 1:06:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5273420953743235940L;
	private String email;
	private String password;
	private String mobile;
	private String altEmail;
	private String firstName;
	private String lastName;
	private String company;
	private String imgSrc;
	private Set<Userrecommendation> userrecommendations = new HashSet<Userrecommendation>(
			0);

	public User() {
	}

	public User(String email, String mobile, String firstName, String lastName,
			String imgSrc) {
		this.email = email;
		this.mobile = mobile;
		this.firstName = firstName;
		this.lastName = lastName;
		this.imgSrc = imgSrc;
	}

	public User(String email, String password, String mobile, String altEmail,
			String firstName, String lastName, String company, String imgSrc,
			Set<Userrecommendation> userrecommendations) {
		this.email = email;
		this.password = password;
		this.mobile = mobile;
		this.altEmail = altEmail;
		this.firstName = firstName;
		this.lastName = lastName;
		this.company = company;
		this.imgSrc = imgSrc;
		this.userrecommendations = userrecommendations;
	}

	@Id
	@Column(name = "Email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Mobile",  length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "AltEmail", length = 100)
	public String getAltEmail() {
		return this.altEmail;
	}

	public void setAltEmail(String altEmail) {
		this.altEmail = altEmail;
	}

	@Column(name = "FirstName", nullable = false, length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", nullable = false, length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Company", length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "Img_src", nullable = false, length = 256)
	public String getImgSrc() {
		return this.imgSrc;
	}

	public void setImgSrc(String imgSrc) {
		this.imgSrc = imgSrc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	@JsonIgnore
	public Set<Userrecommendation> getUserrecommendations() {
		return this.userrecommendations;
	}

	public void setUserrecommendations(
			Set<Userrecommendation> userrecommendations) {
		this.userrecommendations = userrecommendations;
	}

}
